version: '3.8'

services:
    nginx:
        volumes:
            - ./api:/var/www/api
        labels:
            - traefik.enable=true
            - traefik.http.routers.holmes-app.rule=HostRegexp(`holmes.dev`,`{subdomain:.+}.holmes.dev`)
            - traefik.http.routers.holmes-app-ssl.rule=HostRegexp(`holmes.dev`,`{subdomain:.+}.holmes.dev`)
            - traefik.http.routers.holmes-app-ssl.entrypoints=webs,web
            - traefik.http.routers.holmes-app-ssl.tls=true
            - traefik.http.services.holmes-app-ssl.loadbalancer.server.port=443
            - traefik.http.services.holmes-app-ssl.loadbalancer.server.scheme=https

    mail:
        image: maildev/maildev
        container_name: "holmes_mail"
        ports:
            - "1080:1080"
            - "1025:1025"
        networks: [ default ]

    mysql:
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql

    php: &php_container
        links:
            - mysql
            - mail
        build:
            context: ./
            dockerfile: config/php/Dockerfile
            target: php_dev

    php_worker:
        <<: *php_container

networks:
    default:
        external: true
        name: proxy