version: '3.8'

services:
    nginx:
        env_file:
            - .env
            - .env.local
        build:
            context: config/nginx
            args:
                API_DOMAIN: "${API_DOMAIN:-localhost}"
        container_name: 'holmes_nginx'
        volumes:
            - api-volume:/var/www/api
        ports:
            - "443:443"
            - "80:80"
        links: [ php ]
        networks: [ default ]

    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        container_name: 'holmes_mysql'
        environment:
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "user"
            MYSQL_ROOT_PASSWORD: "root"
        networks: [ default ]
        volumes:
            - mysql-volume:/var/lib/mysql

    php: &php_container
        build:
            context: ./
            dockerfile: config/php/Dockerfile
            target: php_prod
        container_name: 'holmes_php'
        networks: [ default ]
        volumes:
            - api-volume:/var/www/api
        links:
            - mysql
        depends_on:
            - mysql

    php_worker:
        <<: *php_container
        container_name: 'holmes_php_worker'
        build:
            context: ./
            dockerfile: config/php/Dockerfile
            target: php_worker

networks:
    default:
        external: true
        name: holmes_network

volumes:
    api-volume:
    mysql-volume:
