version: '3.8'

services:
    nginx:
        build:
            context: config/nginx
        container_name: 'holmes_nginx'
        volumes:
            - ./api:/var/www/api
            - ./logs/nginx:/var/log/nginx
        expose: [ 80, 443 ]
        links: [ php ]
        networks: [ default ]

    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        container_name: 'holmes_mysql'
        environment:
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "user"
            MYSQL_ROOT_PASSWORD: "root"
        networks: [ default ]
        expose: [ 3306 ]
        volumes:
            - mysql-volume:/var/lib/mysql

    php: &php_container
        build:
            context: ./
            dockerfile: config/php/Dockerfile
            target: php_prod
        container_name: 'holmes_php'
        networks: [ default ]
        volumes:
            - ./api:/var/www/api
            - ./logs/app:/var/www/api/var/log
        links:
            - mysql
        depends_on:
            - mysql

    php_worker:
        <<: *php_container
        container_name: 'holmes_php_worker'
        build:
            context: ./
            dockerfile: config/php/Dockerfile
            target: php_worker

networks:
    default:
        external: true
        name: holmes_network

volumes:
    mysql-volume:
