#framework:
#    mailer:
#        dsn: '%env(MAILER_DSN)%'

knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_ID)%'
            client_secret: '%env(GOOGLE_SECRET)%'
            redirect_route: connect_check_google
            redirect_params: {}
        facebook:
            client_id: '%env(FACEBOOK_ID)%'
            client_secret: '%env(FACEBOOK_SECRET)%'
            type: facebook
            redirect_route: connect_check_facebook
            redirect_params: { }
            graph_api_version: v2.12

        vkontakte:
            type: vkontakte
            client_id: '%env(VK_ID)%'
            client_secret: '%env(VK_SECRET)%'
            redirect_route: connect_check_vkontakte
            redirect_params: { }
        odnoklassniki:
            type: generic
            provider_class: Aego\OAuth2\Client\Provider\Odnoklassniki
            client_id: '%env(OK_ID)%'
            client_secret: '%env(OK_SECRET)%'
            redirect_route: connect_check_odnoklassniki
            redirect_params: { }
            provider_options:
                clientPublic: '%env(OK_PUBLIC)%'
