framework:
    notifier:
        texter_transports:
            gatewayapi: '%env(GATEWAYAPI_DSN)%'
        channel_policy:
            urgent: ['sms']
            high: ['sms']
            medium: ['sms']
            low: ['sms']
        admin_recipients:
            - { email: dev.maxim.antonisin@gmail.com }
