parameters:
    VERIFICATION_LIMIT:  '%env(VERIFICATION_LIMIT)%'
    PROXY:  '%env(PROXY)%'
    MAILER_FROM: '%env(MAILER_FROM)%'
    MAILER_FROM_NAME: '%env(MAILER_FROM_NAME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\EventListener\CorsListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest,  priority: 300}
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    App\EventListener\RequestListener:
        arguments: ['@router', '@request_stack']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
