controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

rest_controllers:
    resource: ../../src/Controller/
    type    : annotation
    prefix  : /api/v1
